apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: oci.earelin.org/tenda/gateway:latest
        name: gateway
        resources: {}
        imagePullPolicy: Never
status: {}
