version: 2
updates:
   - package-ecosystem: "github-actions"
     directory: "/"
     schedule:
       interval: "weekly"
   - package-ecosystem: "gradle"
     directory: "/services-catalog-service"
     schedule:
       interval: "weekly"
