services:
  kafka:
    image: 'bitnami/kafka:3.4'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092

  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
