name: CD - Commons
run-name: CD - Commons - ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - 'trunk'
    paths:
      - 'services/commons/gradle.properties'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/commons
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run clean with Gradle Wrapper
      run: ./gradlew clean
    - name: Run publish with Gradle Wrapper
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
